[package]
name = "tinygraph_x_rust"
version = "0.1.0"
authors = ["Nicolas Zordan <nicolas.zordan.tek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
arrayvec = "0.7"